### ISSUE TITLE
Custom images aren't rendered?

### ISSUE THREAD

**Issue by SamuelMarks** [jumpkick/graphviz-preview#5]
Handy package, but unfortunately it doesn't show images.

This draws a blank graph:
```
digraph graphname {
    cloud[shape=none, label="", image="cloud.png"];
}
```

However it renders fine with:
```
dot -Tpng test.dot -o test.png
```

**Comment by jumpkick** [comment]
The package is basically a mashup of the HTML preview panel and viz.js.

I've never used images with graphviz, I'm not sure if viz.js supports them.... If it does most likely it can not locate the image file which is why it would give you a blank.  

One thing to try would be to give the absolute path to the file and see if that renders anything.  If it does then maybe there is a hack that can be done either changing the working directory of atom or perhaps adding a base URL tag with the directory of the .dot file.

**Comment by jumpkick** [comment]
Yeah, so I tried with an absolute URL and it failed.

Unfortunately, when I looked upstream I found that viz.js doesn't implement graphics loading.   See these tickets:
https://github.com/mdaines/viz.js/issues/24
https://github.com/mdaines/viz.js/issues/28
https://github.com/mdaines/viz.js/issues/35
